# version: CodeDeploy 버전, 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생함.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# hooks: CodeDeploy 배포 단계에서 실행할 명령어를 지정함.
hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    # location: 배포파일 경로
    - location: start.sh
    # timeout: 스크립트 60초 이상 수행 시 실패 처리
      timeout: 60
    # ec2-user 권한으로 실행
      runas: ec2-user

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user